# Generated by Django 4.0.1 on 2022-01-27 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_title', models.CharField(blank=True, max_length=15, null=True)),
                ('sender_detail', models.CharField(blank=True, max_length=15, null=True)),
                ('receiver_detail', models.CharField(blank=True, max_length=15, null=True)),
                ('amount_transacted', models.IntegerField(default=0)),
                ('account_number', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.CharField(blank=True, max_length=15, null=True)),
                ('bank_of_receiver', models.CharField(blank=True, max_length=15)),
                ('date_of_trans', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('account', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('bank', models.CharField(choices=[('DIAMOND BANK', 'DIAMOND BANK'), ('UBA BANK', 'UBA BANK'), ('ACCESS BANK', 'ACCESS BANK'), ('ZENITH BANK', 'ZENITH BANK'), ('FIRST BANK', 'FIRST BANK')], max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('date_opened', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('records', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bankapp.transactions')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
