# Generated by Django 4.0.1 on 2022-03-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='bank',
            field=models.CharField(choices=[('DIAMOND BANK', 'DIAMOND BANK'), ('UBA BANK', 'UBA BANK'), ('ACCESS BANK', 'ACCESS BANK'), ('ZENITH BANK', 'ZENITH BANK'), ('FIRST BANK', 'FIRST BANK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='account_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='bank_of_receiver',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='receiver_detail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='sender_detail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='trans_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
